# Generated by Django 4.1.4 on 2023-04-24 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('account_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('account_name', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('distination_url', models.CharField(max_length=200)),
                ('http_method', models.CharField(max_length=100)),
                ('headers', models.JSONField(max_length=400)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
    ]
